version: '3.9'
networks:
  server:
    external: true
services:
  mohammad:
    container_name: mohammad
    restart: always
    networks:
      server:
        aliases:
          - mohammad
    build: 
      context: ./web
      args:
        - PORT=${PORT}
        - NPM_TOKEN=${NPM_TOKEN}
    env_file:
      - .env
    volumes:
      - ./web:/usr/local/share/mohammad.dev
  adminmohammad:
    container_name: adminmohammad
    restart: always
    networks:
      server:
        aliases:
          - adminmohammad
    build: 
      context: ./admin
      args:
        - PORT=${PORT}
    env_file:
      - .env
    volumes:
      - ./admin:/usr/local/share/admin.mohammad.dev