version: '3.9'
networks:
  server:
    external: true
services:
  mohammad:
    container_name: mohammad
    restart: always
    networks:
      server:
        aliases:
          - mohammad
    build: 
      context: ./web
      args:
        - PORT=${PORT}
        - NPM_TOKEN=${NPM_TOKEN}
    env_file:
      - .env
    volumes:
      - ./web:/usr/local/share/mohammad.dev
    depends_on:
      - dbmohammad
      - staticmohammad
  dbmohammad:
    container_name: dbmohammad
    image: postgres
    restart: always
    networks:
      server:
        aliases:
          - dbmohammad
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
  staticmohammad:
    container_name: staticmohammad
    image: mohammaddev/static_content_server
    restart: always
    networks:
      server:
        aliases:
          - staticmohammad
    env_file:
      - .env.static_content_server
    volumes:
      - ./static:/usr/local/share/static_content_server/static
    depends_on:
      - dbmohammad