name: Deploy to Production
on:
  push:
    branches:
      - main
jobs:
  Generate-Env-File:
    runs-on: ubuntu-22.04
    environment: prod
    env:
      PORT: ${{ vars.PORT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      MOHAMMAD_DB_URL: ${{ secrets.MOHAMMAD_DB_URL }}
      NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate .env
        run: |
          echo "PORT=${PORT}" >> .env;
          echo "NPM_TOKEN=${NPM_TOKEN}" >> .env;
          echo "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}" >> .env;
          echo "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}" >> .env;
          echo "NEXTAUTH_SECRET=${NEXTAUTH_SECRET}" >> .env;
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env;
          echo "MOHAMMAD_DB_URL=${MOHAMMAD_DB_URL}" >> .env;
          echo "NEXTAUTH_URL=${NEXTAUTH_URL}" >> .env;
      - name: Upload .env
        uses: actions/upload-artifact@v3
        with:
          name: .env
          path: .env
  Deploy:
    needs: Generate-Env-File
    runs-on: ubuntu-22.04
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download .env
        uses: actions/download-artifact@v3
        with:
          name: .env
          path: .env
      - name: Delete .env
        uses: geekyeggo/delete-artifact@v2
        with:
          name: .env
      - name: Copy .env to production
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HACKRPROD_HOSTNAME }}
          username: ${{ secrets.HACKRPROD_USER }}
          key: ${{ secrets.HACKRPROD_KEY }}
          port: ${{ secrets.HACKRPROD_PORT }}
          source: ".env/.env"
          target: "~/mohammad.dev/env"
          debug: true
          overwrite: true
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        env:
          PASS: ${{ secrets.HACKRPROD_PASS }}
        with:
          host: ${{ secrets.HACKRPROD_HOSTNAME }}
          username: ${{ secrets.HACKRPROD_USER }}
          key: ${{ secrets.HACKRPROD_KEY }}
          port: ${{ secrets.HACKRPROD_PORT }}
          debug: true
          envs: PASS
          script: |
            cd ~/mohammad.dev
            # unpack .env directory
            rm -rf .env
            mv env/.env/.env .env
            rm -rf env
            # pull latest changes
            git reset --hard
            git pull
            # start docker compose
            echo $PASS | sudo -S docker-compose up -d --build --force-recreate